Repository CSC207-2023Y-UofT/project-notes-2-text, pull requests merged in 2023-08, with the labels that each got.

#7 File sharing
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/notes2text/file_sharing/adapters/ThirdPartySender.java
  app/src/main/java/com/example/notes2text/file_sharing/use_case/FileSharingModel.java
  app/src/main/java/com/example/notes2text/file_sharing/use_case/MyFileProvider.java
  app/src/main/java/com/example/notes2text/file_sharing/use_case/ShareObserver.java
  app/src/main/java/com/example/notes2text/file_sharing/use_case/ThirdParShareUseCase.java
  app/src/main/java/com/example/notes2text/file_sharing/use_case/ThirdPartyOutputBoundary.java
  app/src/main/java/com/example/notes2text/file_sharing/use_case/ThirdPartyOutputModel.java
  app/src/main/java/com/example/notes2text/usecases/FileMenuInteractor.java
  app/src/main/res/xml/file_paths.xml
Labels: enhancement

#64 Update README.md How to Run
  README.md
Labels: documentation

#53 Folder creation
  app/src/main/java/com/example/notes2text/adapters/CreateFolderController.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryAccessOutputBoundary.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryAccessPresenter.java
  app/src/main/java/com/example/notes2text/adapters/fragments/DirectoryAccessController.java
  app/src/main/java/com/example/notes2text/fileselection/usecases/SelectionMenuInteractor.java
  app/src/main/java/com/example/notes2text/usecases/FolderCreationInteractor.java
  app/src/main/java/com/example/notes2text/usecases/FolderFactory.java
  app/src/main/res/layout/dialog_folder_create.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#65 Files are saved in the correct location and user can return to direct…
  app/src/main/java/com/example/notes2text/adapters/FileEditingAdapters/FileEditorActivity.java
  app/src/main/java/com/example/notes2text/adapters/FileEditingAdapters/SavePopUpActivity.java
Labels: bug

#71 Update README.md on UNIT TESTING
  README.md
Labels: documentation

#66 Rename file
  app/src/main/java/com/example/notes2text/adapters/CreateFolderController.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryActivity.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryRefreshOutputBoundary.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryRefreshPresenter.java
  app/src/main/java/com/example/notes2text/adapters/FileListAdaptor.java
  app/src/main/java/com/example/notes2text/adapters/FileMenuController.java
  app/src/main/java/com/example/notes2text/adapters/RenameController.java
  app/src/main/java/com/example/notes2text/adapters/fragments/DirectoryAccessController.java
  app/src/main/java/com/example/notes2text/usecases/FileMenuInputBoundary.java
  app/src/main/java/com/example/notes2text/usecases/FileMenuInteractor.java
  app/src/main/java/com/example/notes2text/usecases/FileRenameInteractor.java
  app/src/main/java/com/example/notes2text/usecases/FolderCreationInteractor.java
  app/src/main/res/layout/dialog_rename_file.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#78 Adding helper functions to fix code smells and comments
  app/src/main/java/com/example/notes2text/adapters/FileEditingAdapters/FileEditorActivity.java
  app/src/main/java/com/example/notes2text/adapters/FileEditingAdapters/SavePopUpActivity.java
Labels: documentation, enhancement

#79 Log n doc(additional dir feature)
  app/src/main/java/com/example/notes2text/adapters/DirectoryAdapters/CreateFolderController.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryAdapters/DirectoryRefreshOutputBoundary.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryAdapters/DirectoryRefreshPresenter.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryAdapters/FileListAdaptor.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryAdapters/FileMenuController.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryAdapters/RenameController.java
  app/src/main/java/com/example/notes2text/adapters/DirectoryAdapters/fragments/DirectoryAccessController.java
  app/src/main/java/com/example/notes2text/adapters/FileSharingAdapters/ThirdPartySender.java
  app/src/main/java/com/example/notes2text/usecases/DirectoryUseCases/FileMenuInteractor.java
  app/src/main/java/com/example/notes2text/usecases/DirectoryUseCases/FileRenameInteractor.java
  app/src/main/java/com/example/notes2text/usecases/DirectoryUseCases/FolderCreationInteractor.java
  app/src/main/java/com/example/notes2text/usecases/DirectoryUseCases/FolderFactory.java
  app/src/main/java/com/example/notes2text/usecases/FileSharingUseCases/FileSharingModel.java
  app/src/main/java/com/example/notes2text/usecases/FileSharingUseCases/MyFileProvider.java
  app/src/main/java/com/example/notes2text/usecases/FileSharingUseCases/ThirdParShareUseCase.java
  app/src/main/java/com/example/notes2text/usecases/FileSharingUseCases/ThirdPartyOutputBoundary.java
  app/src/main/java/com/example/notes2text/usecases/FileSharingUseCases/ThirdPartyOutputModel.java
Labels: bug, documentation

#92 Naming Update (Additional dir features)
  app/src/main/java/com/example/notes2text/adapters/directoryadapters/CreateFolderController.java
  app/src/main/java/com/example/notes2text/adapters/directoryadapters/FileListAdaptor.java
  app/src/main/java/com/example/notes2text/adapters/directoryadapters/RenameController.java
  app/src/main/java/com/example/notes2text/adapters/directoryadapters/fragments/DirectoryAccessController.java
  app/src/main/java/com/example/notes2text/usecases/directoryusecases/FileMenuInteractor.java
  app/src/main/java/com/example/notes2text/usecases/directoryusecases/FolderCreationInteractor.java
  app/src/main/java/com/example/notes2text/usecases/filesharingusecases/FileSharingModel.java
  app/src/main/java/com/example/notes2text/usecases/filesharingusecases/ThirdParShareUseCase.java
  app/src/main/java/com/example/notes2text/usecases/filesharingusecases/ThirdPartyOutputModel.java
Labels: enhancement
